# helm diff upgrade --install -n localhost proxysql-basic-pgsql ./charts/proxysql/ -f ./examples/proxysql/proxysql-basic-pgsql.values.yaml
# helm diff upgrade --install -n localhost postgresql bitnami/postgresql --version 18.2.0 --set auth.postgresPassword=postgres # install postgres with user/pass postgres/postgres
proxysql:
  podAnnotations:
    app.config/checksum: v2
  autoscaling:
    minReplicas: 1
  volumes:
    - name: proxysql-config
      mountPath: /etc/proxysql.cnf
      subPath: proxysql.cnf
      readOnly: true
      configMap:
        name: proxysql-basic-pgsql
  envFrom:
    secret: proxysql-basic-pgsql

  containerPort: 5432
  service:
    port: 5432
  app:
    databaseType: "pgsql"
    servers:
      - hostname: postgresql.localhost
    users:
      - username: postgres
        password: postgres
