apiVersion: v2
name: resource
description: A Helm chart for Kubernetes to create any type of k8s resources(or CRDs) by passing the resources `apiVersion`, `kind`, `metadata` and `spec` standard resource fields
type: application
version: 0.1.1
appVersion: "0.1.0"
