{{- if .Values.scheduledRestart.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "base.fullname" . }}-proxysql-scheduled-restart"
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "base.fullname" . }}-proxysql-scheduled-restart"
subjects:
  - kind: ServiceAccount
    name: {{ (first .Values.scheduledRestart.jobs).serviceAccount.name }}
    namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "base.fullname" . }}-proxysql-scheduled-restart"
{{- end }}
