apiVersion: v2
name: weave-scope
version: 1.0.3
appVersion: 1.10.2
description: A Helm chart for the Weave Scope cluster visualizer.
keywords:
  - containers
  - dashboard
  - monitoring
home: https://www.weave.works/oss/scope/
sources:
  - https://github.com/weaveworks/scope
maintainers:
  - name: omkensey
    email: github@orion-com.com
icon: https://avatars1.githubusercontent.com/u/9976052?s=64
dependencies:
  - name: weave-scope-agent
    version: 0.10.1
    repository: "file://charts/weave-scope-agent"
  - name: weave-scope-frontend
    version: 0.10.0
    repository: "file://charts/weave-scope-frontend"
